### PR TITLE
track build time and warn every 15 minutes

### PR DESCRIPTION
**Pull request by TheFirstAvenger**

### CODE REVIEW

**Comment by msawka** [comment]
* Can you use the existing [workflow_start_time](https://github.com/OpenAperture/workflow_orchestrator_api/blob/master/lib/workflow_orchestrator_api/workflow.ex#L70) rather than having to create a another timer?

**Comment by TheFirstAvenger** [comment]
The way it is implemented, it will notify every 15 minutes, since we update the value to the current time after popping a warning. If we used workflow start, we wouldn't be able to do that. Also, it is timing just the build portion, not the entire workflow.

**Comment by msawka** [comment]
Then let's add the interval piece to the builder request.  It seems cleaner than having another pid to manage.

**Comment by TheFirstAvenger** [comment]
The issue with putting it in the builder request is that we are checking inside the async command's interval check (a closure), which means that to update it after a warning, we would both have to pass the builder all the way down through DeploymentRepo, Docker, and into the AsyncCommand, and send it all the way back up the chain again (making it tightly coupled all the way through). The other way we could do it is similar to the way we initially did the async command, which was to run the entire existing top level call in a task, with a periodic check to see if it was completed, but that too would include an additional pid (plus a bunch of other stuff).

**Comment by msawka** [comment]
Ok, so what if we created a separate MilestoneMonitor process, given the BuilderRequest initially, which can monitor each stage (config) and (build).  It's responsible for monitoring the total time, and increment time.  If if needs to push notifications (after the 15 minute windows), it'll do it.  That would keep it separate from the "build" logic.  Really we're losing [this](https://github.com/OpenAperture/builder/blob/warn_on_long_build/lib/builder/milestones/build.ex#L50) message in the event_log anyway, since the request is being updated.  It would be the same deal in the new scheme.  

I think it would also be worth-while adding a new option to the notifications custom config(openaperture.json).  It's populated during the config stage, so we could send emails during build if needed.

**Comment by TheFirstAvenger** [comment]
Replaced by https://github.com/OpenAperture/builder/pull/13

**Pull request closed without merging**
